### ISSUE TITLE
Adaugare suport pentru CNP-uri generate in strainatate

### ISSUE THREAD

**Issue by Nicu-Ducal** [alceanicu/romanian-personal-identity-code-validator#18]
Salut, este nevoie de adaugat suport pentru CNP-urile obtinute in strainate, in cadrul ambasadelor/sectiilor consulare. Acestea au codul JJ = 80, care nu este in lista.

+ @alceanicu recomand mutarea acelor coduri intr-un JSON fisier, sa fie mai simplu ulterior de actualizat.

**Comment by Nicu-Ducal** [comment]
#17 fixes this

**Comment by Draganoid345** [comment]
Nu am gasit un articol in lege unde sunt specificate codurile posibile, insa poti face referinta aici https://ro.wikipedia.org/wiki/Discu%C8%9Bie:Cod_numeric_personal_(Rom%C3%A2nia)#JJ_la_romanii_nascuti_in_strainatate:~:text=JJ%20la%20romanii%20nascuti%20in%20strainatate%5B,%2C%207%20ianuarie%201016%2C%2015%3A59%20CET

**Comment by alceanicu** [comment]
V1.1.2 - update npm
