### ISSUE TITLE
CNP validation

### ISSUE THREAD

**Issue by florian-g-** [alceanicu/romanian-personal-identity-code-validator#9]
One thing I recognized: a CNP with a prefixed letter processed as valid.
Example:
5110102441483     --> Valid (and it actually is) 
x5110102441483   --> Valid (but actually it is not) 

Thanks for the lib.

**Comment by alceanicu** [comment]
fixit

**Comment by florian-g-** [comment]
I was about to give you a PR but anyway, thanks for the very quick bugfix :+1: Issue is fixed
